language: objective-c

osx_image: xcode9.4
xcode_project: platforms/ios/zeptobird.xcodeproj
xcode_scheme: zeptobird

before_script:
    - xcodebuild -project platforms/ios/zeptobird.xcodeproj -list
    - xcodebuild -project platforms/ios/zeptobird.xcodeproj -target zeptobird -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
