language: objective-c

osx_image: xcode7.3
xcode_project: ios/zeptobird.xcodeproj

before_script:
    - xcodebuild -project ios/zeptobird.xcodeproj -target zeptobird -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
